### ISSUE TITLE
Error whith cert? SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by azacchino** [deploykit/telegraph-api#5]
I have error using this lib throw composer.

`use Deploykit\Telegraph\Client as telegraph;`
`$telegraph = new telegraph();`
`$tphAcc = $telegraph->createAccount('test', 'Test', 'http://example.com.ar');`

Trace:
PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in ~\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
Stack trace:
#0 ~\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in ~\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
Stack trace:
#1 ~\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#0 ~\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#2 ~\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleH in ~\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187
#1 ~\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 ~\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleH in ~\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by alexsoft** [comment]
Hello, @died74.
I am afraid it's something wrong with curl library. Because I just used your code exactly and it worked. Cannot reproduce it for now :(

**Comment by azacchino** [comment]
Wow it's was a fast reply!

I google for this and find this: https://stackoverflow.com/a/16495053

> 
> 
> It's a pretty common problem in Windows. You need just to set cacert.pem to curl.cainfo.
> 
> Since PHP 5.3.7 you could do:
>     download https://curl.haxx.se/ca/cacert.pem and save it somewhere.
>     update php.ini -- add curl.cainfo = "PATH_TO/cacert.pem"
> Otherwise you will need to do the following for every cURL resource:
> curl_setopt ($ch, CURLOPT_CAINFO, "PATH_TO/cacert.pem");

and works!

**Comment by alexsoft** [comment]
@died74 thanks! Do my best to react quickly.
Oh, happy you found a solution.
Will be grateful for your feedback
