### ISSUE TITLE
Error Handle

### ISSUE THREAD

**Issue by azacchino** [deploykit/telegraph-api#6]
**Code**
`$telegraph = new telegraph();`
`$tphAcc = $telegraph->createAccount('test', 'Test', `'http://example.com.ar');`
`$page = $telegraph->createPage($tphAcc,"Mi Titulo","Aca el contenido");`

**Apache Log**
> PHP Notice:  
> Undefined index: result in ~/vendor/deploykit/telegraph-api/src/Client.php on line 103
> PHP Fatal error:  
> Uncaught TypeError: Argument 1 passed to Deploykit\\Telegraph\\Entities\\BaseEntity::__construct() must be of the type array, null given, called in ~/vendor/deploykit/telegraph-api/src/Client.php on line 103 and defined in ~/vendor/deploykit/telegraph-api/src/Entities/BaseEntity.php:9
> 
> Stack trace:
> #0 ~/vendor/deploykit/telegraph-api/src/Client.php(103): Deploykit\\Telegraph\\Entities\\BaseEntity->__construct(NULL)
> #1 ~/src/publish.php(37): Deploykit\\Telegraph\\Client->createPage(Object(Deploykit\\Telegraph\\Entities\\Account), 'Mi Titulo', 'Aca el contenid...')
> #2 {main}\n  thrown in ~/vendor/deploykit/telegraph-api/src/Entities/BaseEntity.php on line 9

i put a  echo $response->getBody()->getContents(); in line 102 of Clien-php file and obtain {"ok":false,"error":"CONTENT_FORMAT_INVALID"

This proyect it's great. Buy was no error handle :-(. When a content is not array or author url is not a well formed URL the APIclient crash. This is because the response array  (in error) not contain "response" tag. 

i suggest read the "OK" TAG (boolean) 

Error response example {"ok":false,"error":"CONTENT_FORMAT_INVALID"} or {"ok":false,"error":"AUTHOR_URL_INVALID"}

**Comment by alexsoft** [comment]
@died74, well the problem with createPage is not only about error handling, but also a way of managing that content. We are still trying to find time to make improvements to this library.
And as you started using this library, we'll do our best to make it completely usable asap. Thanks for understanding.

By the way, we a Roadmap project on GitHub - https://github.com/deploykit/telegraph-api/projects/1

**Comment by alexsoft** [comment]
@died74 for now added a simple exception. And working with creating content pages is planned, will try to do it asap. Thanks for your feedback.
